### ISSUE TITLE
启动tank时会报错，tank访问不了

### ISSUE THREAD

**Issue by fanxinxin** [XiaoMi/minos#42]
innosql@db-43:~/raolh/bigdata/minos$ ./build.sh start tank
2015-12-29 14:27:17 Building tank server
2015-12-29 14:27:17 Check and install prerequisite python libraries
2015-12-29 14:27:17 Installing django
Downloading/unpacking django>=1.5.5
  Downloading Django-1.9-py2.py3-none-any.whl (6.6MB): 6.6MB downloaded
Installing collected packages: django
Compiling /mnt/ddb/1/innosql/minos/build/env/build/django/django/conf/app_template/apps.py ...
SyntaxError: ('invalid syntax', ('/mnt/ddb/1/innosql/minos/build/env/build/django/django/conf/app_template/apps.py', 4, 7, 'class {{ camel_case_app_name }}Config(AppConfig):\n'))

Compiling /mnt/ddb/1/innosql/minos/build/env/build/django/django/conf/app_template/models.py ...
SyntaxError: ('invalid syntax', ('/mnt/ddb/1/innosql/minos/build/env/build/django/django/conf/app_template/models.py', 1, 26, '{{ unicode_literals }}from django.db import models\n'))

Successfully installed django
Cleaning up...
2015-12-29 14:27:24 The component tank is built successfully
2015-12-29 14:27:24 Starting Tank server
Unknown command: 'syncdb'
Type 'manage.py help' for usage.
2015-12-29 14:27:26 Start Tank server success

虽然显示启动成功，但是通过ip:port无法访问，查看log日志有如下报错：

Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/home/innosql/raolh/bigdata/minos/build/env/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 158, in __call__
    self.load_middleware()
  File "/home/innosql/raolh/bigdata/minos/build/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 51, in load_middleware
    mw_class = import_string(middleware_path)
  File "/home/innosql/raolh/bigdata/minos/build/env/local/lib/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/innosql/raolh/bigdata/minos/build/env/local/lib/python2.7/site-packages/django/contrib/auth/middleware.py", line 3, in <module>
    from django.contrib.auth.backends import RemoteUserBackend
  File "/home/innosql/raolh/bigdata/minos/build/env/local/lib/python2.7/site-packages/django/contrib/auth/backends.py", line 4, in <module>
    from django.contrib.auth.models import Permission
  File "/home/innosql/raolh/bigdata/minos/build/env/local/lib/python2.7/site-packages/django/contrib/auth/models.py", line 6, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "/home/innosql/raolh/bigdata/minos/build/env/local/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 159, in <module>
    class ContentType(models.Model):
  File "/home/innosql/raolh/bigdata/minos/build/env/local/lib/python2.7/site-packages/django/db/models/base.py", line 103, in __new__
    "application was loaded. " % (module, name))
RuntimeError: Model class django.contrib.contenttypes.models.ContentType doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. 
[29/Dec/2015 15:28:39] "GET /favicon.ico HTTP/1.1" 500 59

这个问题是不是和下载的django版本有关系 如何解决？

**Comment by YxAc** [comment]
@participant，跟django版本有关，看下载的是1.9，syncdb这个命令好像从1.7就改成migrate了，可以
$path_to_minos/build/env/bin/pip uninstall django
$path_to_minos/build/env/bin/pip install django=="1.5.5"
